### ISSUE TITLE
[K3S] SMF/UPF Containers crash

### ISSUE THREAD

**Issue by EmanueleGallone** [Orange-OpenSource/towards5gs-helm#1]
Hi,
I deployed your chart through helm, following your documentation (installed multus and gtp5 kernel module).
Still, I have two containers that are crashing

1) SMF containers logs:

```
2021-06-23T06:52:25ZSMF version: 
	free5GC version: v3.0.5 
	build time:      2021-02-08T20:11:48Z 
	commit hash:     04c01ec5 
	commit time:     2021-01-30T17:01:30Z 
	go version:      go1.14.4 linux/amd64 
2021-06-23T06:52:25ZSMF Log level is set to [info] level 
2021-06-23T06:52:25Zset log level : info 
2021-06-23T06:52:25Zset report call : false 
2021-06-23T06:52:25Zset log level : info 
2021-06-23T06:52:25Zset report call : false 
2021-06-23T06:52:25Zset log level : info 
2021-06-23T06:52:25Zset report call : false 
2021-06-23T06:52:25Zset log level : info 
2021-06-23T06:52:25Zset report call : false 
2021-06-23T06:52:25Zset log level : info 
2021-06-23T06:52:25Zset report call : false 
2021-06-23T06:52:25Zset log level : info 
2021-06-23T06:52:25Zset report call : false 
2021-06-23T06:52:25ZSMF config version [1.0.0] 
2021-06-23T06:52:25ZUE-Routing config version [1.0.0] 
2021-06-23T06:52:25Zsmfconfig Info: Version[1.0.0] Description[SMF initial local configuration] 
2021-06-23T06:52:25ZEndpoints: [10.100.50.233] 
2021-06-23T06:52:25ZServer started 
2021-06-23T06:52:25ZSMF Registration to NRF {ee18fac9-0683-4335-898c-a61271ce3d42 SMF REGISTERED 0 0xc0003e4ca0 0xc0003e4ce0 [] []   [smf-nsmf] [] <nil> [] [] <nil> 0 0 0  <nil> <nil> <nil> <nil> 0xc00030dcc0 <nil> <nil> <nil> <nil> <nil> map[] <nil> false 0xc0003e4b20 false false []} 
2021-06-23T06:52:25ZFailed to listen: listen udp 10.100.50.244:8805: bind: cannot assign requested address 
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb3ab54] 
 
goroutine 1 [running]: 
github.com/free5gc/smf/pfcp/udp.Run(0xd844d8) 
	/go/src/free5gc/NFs/smf/pfcp/udp/udp.go:27 +0x194 
github.com/free5gc/smf/service.(*SMF).Start(0x14c4940) 
	/go/src/free5gc/NFs/smf/service/init.go:281 +0x250 
main.action(0xc0003226e0, 0x0, 0xc000300ff0) 
	/go/src/free5gc/NFs/smf/smf.go:52 +0x107 
github.com/urfave/cli.HandleAction(0xc05ee0, 0xd86098, 0xc0003226e0, 0xc0003226e0, 0x0) 
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x11a 
github.com/urfave/cli.(*App).Run(0xc0003381c0, 0xc00001e180, 0x3, 0x3, 0x0, 0x0) 
	/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:288 +0x649 
main.main() 
	/go/src/free5gc/NFs/smf/smf.go:41 +0x21d 
```

2) UPF container logs:

```
Cannot find device "n6" 
2021-06-23T06:56:45ZConfig: /free5gc/config/..2021_06_23_06_53_31.396199257/upfcfg.yaml 
2021-06-23T06:56:45ZUPF config version [1.0.0] 
2021-06-23T06:56:45ZSet log level: info 
2021-06-23T06:56:45ZSocket bind fail : Cannot assign requested address 
2021-06-23T06:56:45Zgtp5g device named upfgtp created fail 
2021-06-23T06:56:45ZPool is full, it may not belong to this pool 
2021-06-23T06:56:45ZGtp5gDeviceAdd failed 
2021-06-23T06:56:45ZSocket bind fail : Cannot assign requested address 
2021-06-23T06:56:45ZSocket -1 register event in epoll error : Bad file descriptor 
2021-06-23T06:56:45ZPFCP Sock Register to epoll error 
2021-06-23T06:56:45ZCreate PFCP Server for IPv4 error 
2021-06-23T06:56:45ZUPF - PFCP error when UPF initializes 
2021-06-23T06:56:45ZUPF failed to initialize 
2021-06-23T06:56:45ZPool is full, it may not belong to this pool 
2021-06-23T06:56:45ZRemoving DNN routes 
2021-06-23T06:56:45Zif_nametoindex 
2021-06-23T06:56:45ZDelete routing rule to device upfgtp failed: 10.1.0.0/17 
2021-06-23T06:56:45ZUPDK epoll deregister error 
/free5gc/config/wrapper.sh: line 10:    11 Segmentation fault      (core dumped) /free5gc/free5gc-upfd/free5gc-upfd -f /free5gc/config/upfcfg.yaml 
```

apparently the UPF does not find the N6 link;

Do you know how to solve this?

**Comment by raoufkh** [comment]
Hi @EmanueleGallone 

We are currently using the [MACVLAN plugin](https://www.cni.dev/plugins/current/main/macvlan/) for all interfaces added by using multus. Each MACVLAN interface will enslave an interface on the host as described [here](https://www.cni.dev/plugins/current/main/macvlan/).

By default, the n6 interface on the UPF POD will expect the existence of an interface called `eth1` on the host to be created correctly. If you have only one interface on the worker node that hosts the UPF node, you should see [this section](https://github.com/Orange-OpenSource/towards5gs-helm/tree/main/charts/networks5g#configuration).

**Comment by EmanueleGallone** [comment]
Hi @raoufkh 

Thanks for the clarification. I'm actually running a kubernetes cluster (K3S instance) running on multiple physical machines. I was able to retrieve the interface that provides internet connection (enp6s0 in my case) on the worker node in which the UPF pod is being deployed. I edited the _/charts//free5gc/values.yml_, editing the masterIf:
```
  n6network:
    enabled: true
    name: n6network
    masterIf: enp6s0
    subnetIP: 10.100.100.0
    cidr: 24
    gatewayIP: 10.100.100.1
    excludeIP: 10.100.100.254
```

and deployed the chart through helm, to no avail.
The same errors occur. The UPF and SMF pods keep on crashing.

**Comment by raoufkh** [comment]
Hello again

- You say the AMF pod runs perfectly, so I assume that the corresponding k8s node has an interface called `eth0` because this is the one which is enslaved by default by the AMF's n2 interface. Is the N3IWF running too? Can you provide the status of AMF and N3IWF pods using the `kubectl describe pod <pod_name>` command please?
- For the SMF and UPF, can you provide more information about the status of these pods by running these commands (for both SMF and UPF):
1) `kubectl describe pod <pod name>`
2) `kubectl get pod -o yaml <pod name>`

**Comment by EmanueleGallone** [comment]
Hi,
The following list of files contains all the requested output. Let me know if you need anything else. Much obliged for your support.
### AMF

1. [amf.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717031/amf.txt)
2. [amf.yml.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717033/amf.yml.txt)

### N3IWF

1. [n3iwf.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717035/n3iwf.txt)
2. [n3iwf.yml.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717034/n3iwf.yml.txt)

### SMF

1. [smf.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717042/smf.txt)
2. [smf.yml.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717041/smf.yml.txt)

### UPF

1. [upf.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717043/upf.txt)
2. [upf.yml.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717044/upf.yml.txt)

**Comment by raoufkh** [comment]
Can you kill the UPF pod by `kubectl delete pod` and then resend the results for the new pod (another UPF pod will be created to replace the deleted one). Because it seems that your pod is to old and I can only see this event which has been repreduced many times.
`  Warning  BackOff  14s (x534 over 115m)  kubelet  Back-off restarting failed container `

In addition, can you provide the logs from the multus pod that runs on the UPF node (you should do this after the first step such as we can see the new events).

Another k8s resource type to check is `network-attachment-definition`. 
1) `kubectl get network-attachment-definition` ==> you should have `n6network` in the list (tell me only if it exists or not)
2) `kubectl describe network-attachment-definition n6network` ==> the result in a file please

**Comment by EmanueleGallone** [comment]
N6network is present within the network-attachment-definition list.
N6: [n6network.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717302/n6network.txt)
N4: [n4network.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717318/n4network.txt)

UPF: 

1. [upf.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717319/upf.txt)
2. [upf.yml.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717324/upf.yml.txt)


I think that multus is the culprit. I'm detecting a lot of restart events, even though the multus pods keep running
Multus logs: [multus-pod.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717325/multus-pod.txt)

**Comment by raoufkh** [comment]
On the n6network.txt file, I'm seeing that `eth2` is used as a master interface. Does this interface exist on the node? I assume that the response would be no
You should use this configuration when installing the helm chart:
```
...
  n6network:
    enabled: true
    name: n6network
    masterIf: enp6s0
    subnetIP: 10.100.100.0
    cidr: 24
    gatewayIP: 10.100.100.1
...
```
with further customizartion:
- subnetIP and cidr ashould be the same as the subnet of enp6s0 interface
-  gatewayIP should be the IP address of the gateway on the subnet `enp6s0` belongs to (not the IP address of enp6s0 but its gateway)

**Comment by EmanueleGallone** [comment]
Sorry about the `eth2`; it was a typo from an older trial; I've already tried the configuration 

```
  n6network:
    enabled: true
    name: n6network
    masterIf: enp6s0
    subnetIP: 10.100.100.0
    cidr: 24
    gatewayIP: 10.100.100.1
```

I just re-installed the chart through helm with the right interface but the same errors occur

**Comment by raoufkh** [comment]
Can you provide the new logs of multus, upf and smf please?

**Comment by EmanueleGallone** [comment]
Multus logs: [multus.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717450/multus.txt)
N6network: [n6network.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717470/n6network.txt)


`kubectl get logs free5gc-upf`: [upf-logs.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717454/upf-logs.txt)
`kubectl describe pod free5gc-upf` : [upf-describe.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717456/upf-describe.txt)

`kubectl get logs free5gc-smf`: [smf-logs.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717457/smf-logs.txt)
`kubectl describe pod free5gc-smf`: [smf-describe.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717462/smf-describe.txt)

**Comment by raoufkh** [comment]
the description of n4netowk and n2network please as for n2network there is no problem (I'll try to compare)

**Comment by EmanueleGallone** [comment]
N2net: [n2network.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717522/n2network.txt)

N3net: [n3network.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717525/n3network.txt)

N4net: [n4network.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/6717527/n4network.txt)

**Comment by raoufkh** [comment]
It seems like the configuration of networks is good. It may be an issue f using multus with k3s. 
Please see this [issue](https://github.com/k8snetworkplumbingwg/multus-cni/issues/564) on the multus repository. There may be useful comments for you

**Comment by EmanueleGallone** [comment]
I'll take a look on that issue. Thank you. I'll keep this issue open until I find a way to solve this issue and post the solution

**Comment by raoufkh** [comment]
Okay thank you,

And do not forget to make the n6netowk parameters (subnetIP, cidr, gateway) compliant with the ones of `enp6s0` interface

**Comment by rajewluk** [comment]
@EmanueleGallone, please consider using microk8s which is super easy to configure, including multus, and was verified for this set of helm charts.

**Comment by EmanueleGallone** [comment]
Hi @rajewluk thank you, but my idea was to integrate this deployment within an existing infrastracture which uses K3S

**Comment by EmanueleGallone** [comment]
I managed to make the Multus-CNI work within a subset of the K3S cluster's nodes by following this comment
https://github.com/k8snetworkplumbingwg/multus-cni/issues/564#issuecomment-751375274

The _towards5gs-helm_ chart works like a charm!

Closing the issue!
