### ISSUE TITLE
UPF no internet connectivity can't update alpine linux image ?

### ISSUE THREAD

**Issue by krupalb** [Orange-OpenSource/towards5gs-helm#100]
Hi all, 
first off thank you for making the helm scripts!
I seem to have an issue where I'm not getting internet connectivity from the UPF pod. I've setup the free5gc as per the instructions like this?

`microk8s helm -n free5gc install free5gc-v1 towards5gs/free5gc \
  --set global.n3network.masterIf=eth0 \
  --set global.n4network.masterIf=eth0 \
  --set global.n6network.masterIf=eth0 \
  --set global.n6network.subnetIP=10.100.100.0 \
  --set global.n6network.gatewayIP=10.100.100.1 \
  --set free5gc-upf.upf.n6if.ipAddress=10.100.100.111 \`
  
  all the pods are running and I can ping servers on internet via tun interface on UE + you can see i've set the `free5gc-upf.upf.n6if.ipAddress` as well as per the #14 .
  
`$ kubectl --namespace free5gc exec -it $POD_NAME -- ping -I uesimtun0 www.google.com
PING www.google.com (216.58.213.4) from 10.1.0.1 uesimtun0: 56(84) bytes of data.
64 bytes from ber01s14-in-f4.1e100.net (216.58.213.4): icmp_seq=1 ttl=54 time=21.5 ms
`

Now, when I trace route I see that the data is routed through the gateway, like this?

`$ kubectl --namespace free5gc exec -it $POD_NAME -- traceroute -i uesimtun0 www.google.com
traceroute to www.google.com (142.250.187.228), 30 hops max, 60 byte packets
 1  10.1.92.8 (10.1.92.8)  0.747 ms  0.741 ms  0.728 ms
 2  10.100.100.1 (10.100.100.1)  0.725 ms  0.722 ms  0.720 ms
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *`

when I open a shell into the UPF pod, i've these interfaces created.

![image](https://github.com/Orange-OpenSource/towards5gs-helm/assets/19222027/754b5ccd-476d-4e91-acf1-aa9d5294238e)

IP forwarding is also set `cat /proc/sys/net/ipv4/ip_forward` gives 1.

ping to gateway is working but not going further from UPF, but UERANSIM is connecting to internet.

`/free5gc/upf # ping -I n6 10.100.100.1
PING 10.100.100.1 (10.100.100.1): 56 data bytes
64 bytes from 10.100.100.1: seq=0 ttl=255 time=0.188 ms
64 bytes from 10.100.100.1: seq=1 ttl=255 time=0.271 ms
64 bytes from 10.100.100.1: seq=2 ttl=255 time=0.212 ms
^C
--- 10.100.100.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.188/0.223/0.271 ms`

Pinging Google DNS

`/free5gc/upf # ping -I n6 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
^C
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 0 packets received, 100% packet loss`

Pinging Google DNS using eth0 on UPF

`/free5gc/upf # ping -I eth0 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
^C
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 0 packets received, 100% packet loss`

mainly the issue is I'm not able to update the pod?

`/free5gc/upf # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
2 errors; 25 distinct packages available`

Please can you help?

**Comment by krupalb** [comment]
anyone?

**Comment by devopsjourney23** [comment]
You can look into my demo, Hopefully you'll find answer.

https://youtu.be/ZMGsWStz090

**Comment by krupalb** [comment]
> You can look into my demo, Hopefully you'll find answer.
> 
> https://youtu.be/ZMGsWStz090

I've followed your exact steps but still the UPF pod cannot ping 8.8.8.8 ! When I run Calico conf I have two Calico API servers?

**Comment by krupalb** [comment]
Also I have osx as base machine and VMware Fusion and Ubuntu VM as the os for running the cluster.

**Comment by krupalb** [comment]
The issue can be closed, I've managed to re-deploy with the correct Ubuntu Image and Kernel version, and the pings work from UPF and UERANSIM.
