### ISSUE TITLE
About ipv4.ip_forward in UPF POD

### ISSUE THREAD

**Issue by Sniper1-love** [Orange-OpenSource/towards5gs-helm#103]
After I deploy free5gc with kubernetes, I can't ping well. And I check **cat /proc/sys/net/ipv4/ip_forward** find it is 0. When I try to change it to 1, it tells me that It is read-only file and I can not change it. So how I can solve this?

**Comment by raoufkh** [comment]
Hello @Sniper1-love! Can you specify which main CNI plugin are you using in your cluster?

**Comment by brianchennn** [comment]
@raoufkh
I meet the same issue. I use minikube with Calico CNI.

**Comment by danilogranadosg** [comment]
Same issue here. I use kubeadm with Calico CNI. Should I change the CNI to Flannel?

**Comment by devopsjourney23** [comment]
@brianchennn 
With Calico CNI, you need to add IP Forwarding while deploying calico. 
You can check one of my demo video.

https://youtu.be/ZMGsWStz090
