### ISSUE TITLE
UE Ping is not working

### ISSUE THREAD

**Issue by chethantk** [Orange-OpenSource/towards5gs-helm#115]
As below attached image UE tunnel has been created,BUt if we ping its not working.

![Screenshot 2024-04-01 122115](https://github.com/Orange-OpenSource/towards5gs-helm/assets/65939021/803e1ea5-f892-4731-b05a-c90e230f8aa8)

And i had trouble shooted it ,i found that packet forward is the issue,but i tried to excute this command says read only error.
How can solve this issue to enable the packet forwarding 

![Screenshot 2024-04-01 122425](https://github.com/Orange-OpenSource/towards5gs-helm/assets/65939021/b4377aca-1261-4c59-8b31-b41c94d87a62)

And even all the pods are up & running as attached file
![Screenshot 2024-04-01 122955](https://github.com/Orange-OpenSource/towards5gs-helm/assets/65939021/3bf8541b-b2a1-4196-b90b-5d8684513e77)

Can i get  help to solve this error to make uesimtun0 working  ?

**Comment by lyz508** [comment]
Hi @chethantk,
It seems that the correct network policy wasn't set on the Calico CNI plugin. 
You can refer to [this guide](https://docs.tigera.io/calico/latest/reference/host-endpoints/forwarded) for asistance.
Additionally, the check should be performed on the UPF rather than the UE.
Regards,
