### ISSUE TITLE
[New features or request]

### ISSUE THREAD

**Issue by hkerma** [Orange-OpenSource/towards5gs-helm#15]
Hello,

I'd love to see two feature in `towards5gs-helm`:

- [ ] 5G tests (script exists [here](https://github.com/free5gc/free5gc/wiki/Test))
- [ ] Network slicing

For the second one, I am not sure how it would be implemented from a technical aspect. Of course, I am willing to help on these features.

Please tell me your opinion on this!

**Comment by raoufkh** [comment]
Hello @hkerma 

Thank you for suggesting these two features. They both look very interesting. 

For 5G tests, the idea is to implement them using the [test feature of Helm](https://helm.sh/docs/topics/chart_tests/). 
However, I'm not sure it will be possible with current test scripts of Free5GC. In fact, I'm not sure from where the test binaries (e.g. TestRegistration) that are called in the test.sh scripts are generated but I think they are generated from these programs https://github.com/free5gc/free5gc/tree/main/test. 
Looking for example at the registration test, we can see that the [AMF N2 address is hardcoded](https://github.com/free5gc/free5gc/blob/6fecbec878df216cde8e7e92ac7019ef9e0304fe/test/registration_test.go#L38) (that's just an example). 
In the test.sh too there is hardcoded informations like the UESubnetIP. 
Thus, theese tests cannot be run against our implementation of Free5GC on Kubernetes. Creating a topic on the Free5GC forum mentioning this issue to ask the question if separating the configuration of test programs should be useful. 

For network slicing, I am beginner in this field. All I know is that some Free5GC functions support slicing information in their configuration files. In my mind, to deploy a function (e.g. SMF) in two different slices, you just have to deploy it twice with two different configurations. This can be established by using the Helm charts for each network function, where the configuration is always separated from the templates and put in values.yaml.
See the [SMF configuration](https://github.com/Orange-OpenSource/towards5gs-helm/blob/210b06f2802cba72f26492d21a814405d296ae79/charts/free5gc/charts/free5gc-amf/values.yaml#L149) for example.
For more advanced use-cases, you should ask for that on the Free5GC forum. Taking inspiration from this repo is also possible.

Regards,
Abderaouf
