### ISSUE TITLE
Problem deploying free5gc on cluster

### ISSUE THREAD

**Issue by MrBurawski** [Orange-OpenSource/towards5gs-helm#18]
Hello,
I am using the cluster which consists of two laptops connected via the network. I deploy the free5gc charts from the cluster control-plane (all preliminary requirements seem to be fullfilled). However, while all other pods are doployed on the master node, the amf, upf and smf are not initializing on the worker nodes, as on screenshot
![image](https://user-images.githubusercontent.com/83373023/145374639-d0d98d29-2433-48c5-a6f4-430c8aeb6cd6.png)

When describing a pod i get the following message:
[OutputPodDescribe.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/7684053/OutputPodDescribe.txt)

Where it seems, that all the time when adding interfaces, there is some missing link which doesn't allow Multus CNI to create the container:
 Warning  FailedCreatePodSandBox  111s (x184 over 11m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_free5gc-free5gc-smf-smf-68fbcd7db9-dbj8l_5gtest_358cfc0f-40a2-4d02-92e8-d380eb6326bb_0(3ecb690e00ac792823ee8b02226e323a001e05ca8126275b76757a4b1fb171a6): error adding pod 5gtest_free5gc-free5gc-smf-smf-68fbcd7db9-dbj8l to CNI network "multus-cni-network": [5gtest/free5gc-free5gc-smf-smf-68fbcd7db9-dbj8l:n4network-smf]: error adding container to network "n4network-smf": Link not found

What could be the problem here? (Master node is untainted and allows pods scheduling, node103 is on the same laptop with master node and node193 is on the another laptop). 
Should i expect to have all the pods deployed on the single node? Maybe I should try deploying them specifically from the worker nodes? Thank You in advance.

Here is node description:
[NodesDescribe.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/7684148/NodesDescribe.txt)

**Comment by MrBurawski** [comment]
Only master node allows access to the kubectl and therefore to the helm charts. Should i try creating persistent volume on the worker node?

**Comment by fhgrings** [comment]
@MrBurawski Did you create the eth1 interface? It look like UPF error when configuring eth1 tunneling, I guess.

**Comment by navarrothiago** [comment]
@MrBurawski this problem happened with me when I didn't configure properly the interfaces in SMF. Run `ip a` on your node and check the physical interfaces that you want to set the `global.n4network.masterIf` variable.

**Comment by MrBurawski** [comment]
Thanks for everyone who replied. The problem was indeed with the missing configuration of the ip address of a eth0 interface on one of the nodes. In addition, i have also renamed the network interfaces to eth0 and eth1. I will attach the screenshots of the netplan yaml configuration, which is working for my cluster. (sudo nano /etc/netplan/00-installer-config.yaml).
Control-plane:
![image](https://user-images.githubusercontent.com/83373023/147819841-2b6b3bf8-4283-4847-9feb-8764dd48d5d8.png)

Worker node 1:
![image](https://user-images.githubusercontent.com/83373023/147819878-db24bb60-91ff-4f63-804d-08679580347d.png)

Worker node 2:
![unknown](https://user-images.githubusercontent.com/83373023/147819948-8d3cb9ca-27f6-433d-9e67-386cff6d1e29.png)

Therefore, i am closing the issue
