### ISSUE TITLE
Free5gc control plane containers are not running.

### ISSUE THREAD

**Issue by lpureenaece** [Orange-OpenSource/towards5gs-helm#2]
Description:
1. Created a k8s cluster (cluster is up and running).
2. Kubernetes worker node with kernel 5.0.0-23-generic and containing gtp5g kernel module.
3. Add an additional "eth1" interface on worker node.
4. Installed Multus & helm.
5. Created a persistent volume.
6. Execute the command- "**helm -n free5gc-core install --generate-name ./free5gc/**"
7. After that except upf & mongo-db all other pods are stuck at "Init" state.
   
![image](https://user-images.githubusercontent.com/51489848/124590703-13d3f880-de79-11eb-9dda-a0f6f9cc7a93.png)

8. On worker node- 
     # docker images
    o/p 
![image](https://user-images.githubusercontent.com/51489848/124590543-e0916980-de78-11eb-9619-3be734232742.png)

Attached the log files-
    [
![docker_containers_screenshot](https://user-images.githubusercontent.com/51489848/124591500-fb181280-de79-11eb-9c40-c7d4a31b0b9e.PNG)
![docker_containers_screenshot1](https://user-images.githubusercontent.com/51489848/124591506-fce1d600-de79-11eb-9838-16848f5a0c00.PNG)
![docker_images_screenshot](https://user-images.githubusercontent.com/51489848/124591512-fce1d600-de79-11eb-8790-04dee9b47b77.PNG)
![pods_error_screenshot](https://user-images.githubusercontent.com/51489848/124591514-fd7a6c80-de79-11eb-9170-b00cb0893067.PNG)
](url)

**Comment by raoufkh** [comment]
Hi @lpureenaece 

We make use of initContainers to make sure the mongodb is ready (for the nrf) and the nrf is ready (for other control plane network functions). The init containers try to connect the target (mongodb or nrf) via the Kubernetes services which expose them. That means name resolution is required for the communication between control plane network functions and between them and the database. 

First, let's check that DNS is working well in your cluster. 
1) What dns solution are you using?
2) Try to follow the first step described [here](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) by creating the dns-utils pod at the same namespace as Free5GC components and then trying to resolve the IP address of the service exposing the NRF: `kubectl -n free5gc-core exec -i -t dnsutils -- nrf-nnrf`

**Comment by lpureenaece** [comment]
Previously I have created the free5gc pods in namespace "free5gc-core" where "core-dns" pod was in "kube-system" namespace, So I changed the namespace of free5gs pods to "kube-system" and my problem has been solved.

Now able to resolve the IP address of the service exposing the NRF " **kubectl exec -i -t dnsutils -n kube-system -- nslookup nrf-nnrf.kube-system**"

Thanks for your support @raoufkh .

**Comment by raoufkh** [comment]
You're welcome @lpureenaece.  Note that a good implementation of core-dns should ensure name resolution in all cluster namespaces.

I'll close this issue
