### ISSUE TITLE
UERANSIM deployed, can't ping from root on the pod

### ISSUE THREAD

**Issue by MrBurawski** [Orange-OpenSource/towards5gs-helm#21]
Hello,
I am at loss to perform any testing with my cluster. I have free5gc, ueransim installed and running:
![image](https://user-images.githubusercontent.com/83373023/147890519-c1756bac-0783-46d5-98b2-de6386544e20.png)

I can access UE pod and run "ip address" command:
![image](https://user-images.githubusercontent.com/83373023/147890547-4249a0da-1acb-4806-86e6-f7eada075b02.png)

However, I can't run any meaningfull commands since they appear to be not permitted:
![image](https://user-images.githubusercontent.com/83373023/147890559-019e0065-ad55-490c-98a4-c018f3d7885a.png)

I don't know wheter tunl0 is a corretly created TUN interface. Should i expect to see there something else?
I tried to do something to "exec" in privileged mode (which is allowed on the cluster) or smth similar, but it didn't solve the problem.
What can it be?
I attach the output of the "describe" for the UE-pod. There are some messages about bad connectivity which were due to the UE-pod scheduled on  the node whcih was unreachable. Currently UE is deployed on the CONTROL_PLANE node. I am not sure whether there isn't something wrong with IP which it displays, since it's the external interface of the control node.
Thank You in advance for any kind of advice
[UE-pod describe.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/7801379/UE-pod.describe.txt)
.

**Comment by raoufkh** [comment]
Hello @MrBurawski 

The interface that should be created in the UE Pod is called [uesimtun0](https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/docs/demo/Setup-free5gc-and-test-with-UERANSIM.md#test-with-the-tun-interface). If it is not created, it means that the PDU session has not been properly created. So can you show logs of gNB and free5GC functions (AMF, SMF, UPF) please? 

Regards,
Abderaouf

**Comment by MrBurawski** [comment]
Hello
Here are the logs of AMF and results of pod describe:
![image](https://user-images.githubusercontent.com/83373023/148654147-bf3d6bcd-d6c7-42a0-ab2a-15f171a4f565.png)
[AMF.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/7833702/AMF.txt)

Logs of the SMF and pod describe:
![image](https://user-images.githubusercontent.com/83373023/148654282-ec031204-8ce8-4b46-a2e3-c043cdca2c55.png)
[SMF.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/7833705/SMF.txt)


Logs of the UPF and pod describe:
![image](https://user-images.githubusercontent.com/83373023/148654362-046fd85c-37e9-4d93-8568-0c54aed2433f.png)
[UPF.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/7833706/UPF.txt)

As I see, there is some problem in the UPF logs which seems to be related to the message about the iptables, is that so?

**Comment by raoufkh** [comment]
Hello @MrBurawski 

I've never seen this kind of error on the UPF. Maybe the idea is to post that on the Free5GC forum. By looking at internet, it seems that this is a system call error in C language https://github.com/travisghansen/fanout/issues/19

**Comment by raoufkh** [comment]
This issue may be solved by using the last available version of Free5GC (UPF is written in Go instead of C)
