### ISSUE TITLE
UPF locked in ContainerCreating Status

### ISSUE THREAD

**Issue by Duaran** [Orange-OpenSource/towards5gs-helm#23]
Hello everyone,

I tried to deploy the free5gc network with the help of your documentation and this tutorial : 

https://medium.com/rahasak/deploying-5g-core-network-with-free5gc-kubernets-and-helm-charts-29741cea3922

However during the deploying phase the UPF pod stay at the ContainerCreating status like below : 

![image](https://user-images.githubusercontent.com/43369975/148784885-adaa7171-791d-4a49-ad1c-23240a23db0a.png)

It seems to be due to this error : 

![image](https://user-images.githubusercontent.com/43369975/148785243-e8f735b2-4565-453c-add5-a4d45a4cb18f.png)

I read other closed issues which could be compared to this kind of error. That's why I run ip a on other components of free5gc like the smf, amf and udr. (with the result below)

![image](https://user-images.githubusercontent.com/43369975/148785921-535ee7ea-95a5-4bdc-8515-d3f9748d0b88.png)

Does this error happen from the fact that I have only eth0 as network interface and creating a 2nd interface eth1 is needed? Or it is because "Nx" interface aren't renamed eth1 ? (Or maybe something else)

Thank you and have a nice day !

**Comment by raoufkh** [comment]
Hello 

It seems that Multus cannot provide the network N6 to the UPF. I recall that by default, the N6 interface is bound to the interface `eth1` on the host. So, is this interface available on your host? If not please see [Networks configuration](https://medium.com/rahasak/deploying-5g-core-network-with-free5gc-kubernets-and-helm-charts-29741cea3922)

**Comment by ritokispingvin** [comment]
Hi  @raoufkh,
I'm experiencing exactly the same issue with the UPF pod while having 2 NAT interfaces (enp0s3 and enp0s8) + 1 Host only interface (enp0s9) set up in VirtualBox. 
can you please help us how you are created the eth0 and eth1 interfaces?

**Comment by raoufkh** [comment]
Hello @ritokispingvin 

Network interfaces name is important to consider when you configure the free5gc helm charts. You should seee this [section](https://github.com/Orange-OpenSource/towards5gs-helm/tree/main/charts/free5gc#networks-configuration). with the defaul values of the chart and no eth0 and eth1 present on your worker nodes, AMF and SMF should not be created. Can you show the `kubectl describe pod` command for AMF and SMF pods please?

**Comment by ritokispingvin** [comment]
Hi @raoufkh ,

kubectl describe pod for AMF:
![image](https://user-images.githubusercontent.com/81585862/157307655-b7893232-d81c-4164-a78c-a8143d5147d6.png)

kubectl describe pod for SMF:
![image](https://user-images.githubusercontent.com/81585862/157307813-17073501-8fe7-4b1c-954e-6b6fbba79cf9.png)

I found out that I was using eth0 as NAT network and eth1 as host-only network while I think eth1 should have been the NAT network. So I changed it, but issue still there :(
My current network config:
![image](https://user-images.githubusercontent.com/81585862/157308129-895cb21b-d8f5-4c02-a9d9-6ecbc8ab1d5f.png)
![image](https://user-images.githubusercontent.com/81585862/157308252-e9e42693-acc8-419a-b1a3-f15e132462d3.png)
![image](https://user-images.githubusercontent.com/81585862/157308300-3c90f9b9-e83e-4adb-9c42-ebb380071b2e.png)

Error for UPF pod is still exactly same. I've tried minikube, kubeadm with flannel, calio but all has this same issue:
![image](https://user-images.githubusercontent.com/81585862/157308622-ff77a6ad-a663-4cb5-84bd-67f6852f7985.png)

Do I need to modify some IP in the free5gc charts to match my NAT network IP?

Many Thanks and BRs,
Tamas

**Comment by ritokispingvin** [comment]
Hi, 
I don't know what happened but when I deployed kubeadm again and again it started working. It is still really strange and I can not explain why I had this issue with UPF, the only difference is that I make everything slower and waited all pods to be ready before going to next steps.
BRs,
Tamas

**Comment by raoufkh** [comment]
Hi @ritokispingvin 

Good news

Maybe because UPF N6 configuration was wrong, because the descritpion of UPF pod says that the CNI cannot attach the pod to n6network

Bests
Raouf
