### ISSUE TITLE
UPF does not send the PFCP Association Setup Request to SMF, when we create new UFP

### ISSUE THREAD

**Issue by prati08** [Orange-OpenSource/towards5gs-helm#24]
UPF does not send the PFCP Association Setup Request to SMF, when we create new/scale out UFP on the fly.

Because of this smf will be not aware of new upf.

**Comment by raoufkh** [comment]
Hi @prati08 

Regarding 3GPP standards, the UPF may also send Association requests to the SMF. However, this is not implemented in Free5GC. One idea to scale the UPF is to reconfigure the SMF and restrart it but this is not possible with the current version of Free5GC as the SMF is not completely stateless
