### ISSUE TITLE
Running UPF on a separate, no containarized host

### ISSUE THREAD

**Issue by ednaganon** [Orange-OpenSource/towards5gs-helm#25]
Hello, 
I would like to run UPF on a separate h similar to the diagram you  show here:
<img width="465" alt="Setup-free5gc-on-multiple-clusters-and-test-with-UERANSIM-Architecture" src="https://user-images.githubusercontent.com/27771163/150397814-0706c0d8-9ea9-4bea-ac49-320ba2fb6101.png">
 but non containarized, non containerized, so the UPF  interfaces are the host interfaces. What configuration changes should I do in smf configuration so that SMF pod could speak with UPF ? specifically  the n4 network does not work correctly. Should it be omitted and a nodePort service be created instead? what changes should be made to values.yaml?
Thanks, Edna

**Comment by raoufkh** [comment]
Hello

You should adapt the N4 and N3 configuration of SMF and UERANSIM to match with the IP addresses of the host of the UPF. That means, this must be connected to the Kubernetes cluster while each of its interfaces must be in the same network as one interface on the Kubernetes cluster (one node of the cluster)

Bests

**Comment by ednaganon** [comment]
So there is no way to connect towards5gs-helm/free5gc SMF pod to  external UPF which is not  a part of the Kubernetes cluster? Similar to how N2 is exposed by AMF to an external GNB?

 

Thanks,

 

Edna

**Comment by raoufkh** [comment]
You can. You have only to make sure that UPF is listening on an IP address which is in the same network as SMF N4 interface. You can reach this for example by having 2 hosts: 
- `host1` for the Kubernetes cluster with a network interface `eth0` with `IP1`
- `host2` for the UPF with a network interface `eth0` with 'IP2' and which is in the same network as `IP1`

At this stage, make sure that the hosts can communicate via their `eth0` interfaces. Then, you make the SMF N4 interface using the `eth0` of `host` as master interface (see Helm chart values) and you assign `IP3` to it (SMF N4). By choosing `IP3` in the same subnet as `IP1` and `IP2`, the SMF and the UPF will be able to communicate.

Bests,
Abderaouf
