### ISSUE TITLE
Amf pod not using eth0 IP

### ISSUE THREAD

**Issue by nitinrajput1997** [Orange-OpenSource/towards5gs-helm#30]
I have followed this article to deploy free5gc https://medium.com/rahasak/deploying-5g-core-network-with-free5gc-kubernets-and-helm-charts-29741cea3922 .But in amf pod logs , i can see it assigns different ip , but I want it should assign same ip as eth0 of that virtual machine. How can I do that ?

**Comment by raoufkh** [comment]
Hello 

Can you give more details on your architecture? 
The AMF SBI will be listening on the eth0 interface of AMF Pod but not the one of VM.

**Comment by nitinrajput1997** [comment]
Hi @raoufkh ,  suppose I have created on vm with two interface say eth0 and eth1 and have IP's as 192.168.8.94 and  192.168.8.95 respectively. After installing all prerequisite , now we deploy free5gc using "helm -n free5gc install free5gc-v1 towards5gs/free5gc" . When i see the logs pf amf , it shows it assigns ngap_server as unknown IP (say 10.244.120.92/32). Although upf pod remains in contarinerCreating status . But when I tried to change ngap from 10.244.120.92/32 to 192.168.8.94 (eth0) , the amf pods stuck in init status.

Now on another server where UERANSIM is installed , we have to update the config with amf ip address , where i have pasted random ip generated by amf during pod creation as mentioned above i.e 10.244.120.92 with port 38412. After that running gNodeB it stucks with message "establishing connection with 10.244.120.92:38412". 

But I want the free5gc should use server ip and eth0 not there generated one. So that ,it was better for us to understand flow and establish connection between gNodeb also.

**Comment by raoufkh** [comment]
Hello @nitinrajput1997 

Have you modified any values.yaml file?

The default behavior should be: 
- AMF should has 2 interfaces (eth0 and n2) and NGAP server should bind to n2 interface (it's a MacVlan interface)
- gNB has also an N2 interface which allows to reach the AMF, even if it is on another host or k8s cluster. The 2 macvlan interfaces should bind to master interfaces in the same subnet.

Bests
Raouf

**Comment by nitinrajput1997** [comment]
hi @raoufkh , yes I have modified values.yaml . In values.yaml , I have updated ngap ip with my server ip.
Is there any document which I can follow to deploy ?

**Comment by nitinrajput1997** [comment]
Hi @raoufkh , it's better you pls share some document or blog through which we can deploy free5gc helm charts easily

Thanks

**Comment by nitinrajput1997** [comment]
Hi @raoufkh , I have two interface and have install all pre-requisites. After that I'm getting this error of UPF again and again 
![Screenshot from 2022-09-10 22-48-51](https://user-images.githubusercontent.com/63159531/189494776-f055a042-ba02-4800-a203-66d6ee7696b6.png)

**Comment by raoufkh** [comment]
This may occur if the N6 network subnet IP doen't correspond to the subnet of the underyling network interface. In addition, you must provide a real gatewat IP¨

Raouf
