### ISSUE TITLE
webconsole username/password?

### ISSUE THREAD

**Issue by poussa** [Orange-OpenSource/towards5gs-helm#31]
What is the webconsole username and password? It is not `admin/1423`.

**Comment by poussa** [comment]
https://github.com/free5gc/free5gc/wiki/New-Subscriber-via-webconsole#4-use-browser-to-connect-to-webconsole

**Comment by raoufkh** [comment]
Hello

For the Free5GC webconsole:
```
username: admin
password: free5gc
```
