### ISSUE TITLE
Kubectl logs screenshots from pods

### ISSUE THREAD

**Issue by ritokispingvin** [Orange-OpenSource/towards5gs-helm#32]
Hi,
I'm currently writing my master degree thesis on my University and I'm using towards5gs-helm to test with Istio. I can make all the pods running but unfortunately the TUN interface is not created for me because of some issue between AMF/gNb I tried to troubleshoot it but haven't found a solution yet and don't want to run out of time with unnecessary troubleshooting. 
I would like to put some screenshots about the fully working pods into my dissertation. The output of the "kubectl logs podname" shows everything I want. 
Can you please provide some screenshots to me from all the free5gc/ueransim pods when using "kubectl logs" command?
Many thanks!
Best Regards,
Tamas

**Comment by raoufkh** [comment]
Hello! Can you provide your gNB, AMF, SMF and UPF logs please? It will be a good point to start debugging the issue

**Comment by ritokispingvin** [comment]
Hi @raoufkh!
Sorry for the slow answer, some uni stuff was ongoing. Please find the logs below. I think everything works fine unless the gNb, the NAS timer always expires causing DEREGISTRATION.

![ue logs](https://user-images.githubusercontent.com/81585862/162281013-bb820bfd-4244-4cd8-8e51-2410f4e3f6c6.JPG)
![gnb logs](https://user-images.githubusercontent.com/81585862/162281045-36d7d3b0-d4e4-40f9-8139-403f69218663.JPG)
![kubectl logs 1](https://user-images.githubusercontent.com/81585862/162281075-f04c1fb1-a529-4e9d-82fe-a1d6a509815a.JPG)
![kubectl logs 2](https://user-images.githubusercontent.com/81585862/162281095-35ddabf0-9f7c-4102-872f-8b73a1c104aa.JPG)

Regards,
Tamas

**Comment by raoufkh** [comment]
Hello

It seems that the 5G core is not aware of the UE signaling messages. I don't know why the gNB is show `signal lost` before sending anything to the 5G core (this is what I see in the logs). It may be useful to share this issue in the UERANSIM repository.

**Comment by ritokispingvin** [comment]
Hi @raoufkh,
thank you for checking, I have opened a new issue on the UERANSIM hub as you've advised: https://github.com/aligungr/UERANSIM/issues/511
As investigating this issue might take some time, could you please help me out with screenshots to me from all the free5gc/ueransim pods when using "kubectl logs" command?
Best regards,
Tamas

**Comment by ritokispingvin** [comment]
Hi  @raoufkh,
still my problem in the UERANSIM hub is not solved and I would like to put some working pod logs into my thesis. (referencing this git of course). This is to demonstrate the 5G NFs in their working state.
Can you please help me out with 1-1 screenshots from each "kubectl logs" from each pod?
Thank you and best regards,
Tamas
