### ISSUE TITLE
No uesimtun0 interface in UE pod

### ISSUE THREAD

**Issue by anhdangkhoa** [Orange-OpenSource/towards5gs-helm#33]
Hi, I am trying to install free5gc into my VirtualBox VM with **single-node** Kubernetes cluster _(Pod is scheduled to Master node)_
In my VM, I have three interfaces:

- `enp0s3` (NAT interface): IP 10.0.2.15/24 GW 10.0.2.2
- `enp0s8` (Bridge Network): DHCP4
- `enp0s9` (Host-only interface): 192.168.56.200/24

Since the VM **does not** have interface `eth0` and `eth1`. I have reconfigured it with the instruction in [Network configuration](https://github.com/Orange-OpenSource/towards5gs-helm/tree/main/charts/free5gc#networks-configuration):
### Install free5gc
```console
helm -n free5gc install free5gc-v1 towards5gs/free5gc --set global.n2network.masterIf=enp0s3,\
  global.n3network.masterIf=enp0s3,global.n4network.masterIf=enp0s3,\
  global.n6network.masterIf=enp0s3,global.n9network.masterIf=enp0s3,\
  global.n6network.subnetIP=10.0.2.0,global.n6network.gatewayIP=10.0.2.2,\
  free5gc-upf.upf.n6if.ipAddress=10.0.2.15
```
### Install the UERANSIM Helm chart
```console
helm -n free5gc install ueransim towards5gs/ueransim --set\
  global.n2network.masterIf=enp0s3,global.n3network.masterIf=enp0s3
```
### All the pod are running successfully
![image](https://user-images.githubusercontent.com/48313128/163097078-a8fd2c7c-4cf3-4a02-9661-f7d9b6011bde.png)

### However, there is no `uesimtun0` in ue pod as in instruction so that I cannot perform ping test
![image](https://user-images.githubusercontent.com/48313128/163097225-58eb62af-a449-42cd-aaed-248c820bd397.png)

### Here are the `kubectl logs` of AMF, UPF, SMF, gNB and UE
**AMF**
![image](https://user-images.githubusercontent.com/48313128/163097414-a12f47c6-9d76-4e03-b607-bbd010b74c9f.png)
**SMF**
![image](https://user-images.githubusercontent.com/48313128/163097494-9ebbcd35-e528-4d71-ab9f-9e3b0d1d79a1.png)
**UPF**
![image](https://user-images.githubusercontent.com/48313128/163097592-9d2eb256-8d6e-49e5-b742-c04cc5fbfbcb.png)
**gNB**
![image](https://user-images.githubusercontent.com/48313128/163097652-97d044ca-29ca-4f90-b457-4a9a883d7c81.png)
**UE**
![image](https://user-images.githubusercontent.com/48313128/163097726-afec4f2d-1345-40eb-91ec-811ed377159d.png)

**Can you guys help me pinpoint the problem? Thanks in advance!!!**

**Comment by raoufkh** [comment]
Hello 

It seems that the UE cannot authenticate. Have you added the subscriber through the Free5GC webui? If not please refer to [this](https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/docs/demo/Setup-free5gc-and-test-with-UERANSIM.md#add-user-information) to access the webui and then the Free5GC Wiki to do it.

**Comment by anhdangkhoa** [comment]
Thank you,

After I added the subscriber the `uesimtun0` showed up.
