### ISSUE TITLE
Using custom Docker images

### ISSUE THREAD

**Issue by konradkar2** [Orange-OpenSource/towards5gs-helm#38]
Hi
I have two questions.
Could you show me where currenly used Dockerfiles are?
Is there a way to replace docker images repository so I could use my own?

My goal is to use customized docker files(images) so I could have my own, modified version of Free5GC binaries.
Also I would like to add my own software to UE containers.

I'm not really familiar with Helm workflow, but is that possible?  Or should I setup my work in a different way?

**Comment by raoufkh** [comment]
Hello

Our Dockerfiles are hosted on a private repository. However you can use them as base images to build new ones, publish them on Dockerhub and then use them to deploy the project on top of K8s.

For example, within te AMF Helm chart, `amf.image.name` and `amf.image.tag` parameters allow you to specify the Container image to use. Parameters for each Helm chart are availlable on its Readme.

Bests
Raouf

**Comment by raoufkh** [comment]
Do you manage to use custom container images?
