### ISSUE TITLE
NRF pod stuck in "Init" state, awaiting for MongoDB-Where MongoDB pod / containers / svc are in "Running" state.

### ISSUE THREAD

**Issue by lpureenaece** [Orange-OpenSource/towards5gs-helm#4]
Description:

1. Created a k8s cluster (cluster is up and running).
2. Kubernetes worker & master node on kernel 5.4.0-42-generic.
3. Add an additional "eth1" interface on worker node.
4. Installed Multus & helm.
5. Created a persistent volume.
6. Execute the command- "helm -n free5gc-core install --generate-name ./free5gc/"
7. After that except upf & mongo-db all other pods are stuck at "Init" state.
8. All the nodes are in same namespace "kube-system".

Logs are-
cmd- "kubectl -n kube-system get pods --all-namespaces"
![image](https://user-images.githubusercontent.com/51489848/129859904-711d25a3-cb50-4c9c-b14e-7941d30a5eba.png)

cmd- "kubectl describe pod free5gc-1629270501-nrf-694fd8cdd6-cxqvv -n kube-system"
![nrf_describe_log](https://user-images.githubusercontent.com/51489848/129858554-b5e9ef74-555f-49a3-aa35-7ef872f9abb4.PNG)

cmd- "kubectl get pvc,pv,svc --all-namespaces -o wide"
![image](https://user-images.githubusercontent.com/51489848/129860237-63ff82d9-a9d1-4ab0-889b-78b17bc5ae61.png)

cmd- "kubectl get network-Attachment-definitions --all-namespaces"
![image](https://user-images.githubusercontent.com/51489848/129860523-aad2983d-d68f-42f2-a6cb-8c13031037a4.png)

Please assist me.

**Comment by raoufkh** [comment]
Hello! 

Is this issue different from this [one](https://github.com/Orange-OpenSource/towards5gs-helm/issues/2)?

**Comment by raoufkh** [comment]
No more activity!

**Comment by lpureenaece** [comment]
> Hi, I had a similar issue. I don't know if it can be helpful for you but, in my case, it was some problem in the DNS resolution, it was solved restarting coredns.

I have restarted the coredns by command "_**kubectl -n kube-system rollout restart deployment coredns**_" but still same issue.

**Comment by lpureenaece** [comment]
> Hello!
> 
> Is this issue different from this [one](https://github.com/Orange-OpenSource/towards5gs-helm/issues/2)?

This is the same issue, but in previous issue i have created the free5gc and coredns pods in two different namespaces that's why i was facing that issue, when I created both in same namespace the issue has gone. 

But at present both are in same namespace still facing the pods init state issue.

**Comment by ebucchianeri** [comment]
NRF has started due to its init-container which seems to be failing. The NRF init-container basically tries to connect to MongoDB, doing a `nc`. Is the mongoDB reachable using the service name?

**Comment by raoufkh** [comment]
Hi @lpureenaece 

The way the NRF's init container checks for MongoDB readiness has not changed. That means that you are probably encountering DNS problems on your cluster. As @ebucchianeri mentionned, you should try to reach mongodb using its service name from another Pod on the cluster. You can use the busybox image to do it.

Bests

**Comment by lpureenaece** [comment]
> NRF has not started due to its init-container which seems to be failing. The NRF init-container basically tries to connect to MongoDB, doing a `nc`. Is the mongoDB reachable using the service name?

Thanks for the reply @ebucchianeri , Could you please let me know what would be the command to check this mongoDB reachability check using service name?

**Comment by raoufkh** [comment]
First, can you share the logs of the init container please? `kubectl -n <your-namespace> logs <nrf-pod-name> -c wait-mongo`

Then, for debugging, you can run a busybox Pod on the same namespace as MongoDB and then run this command `nslookup <mongo-service-name>` inside the Pod. More reading [here]

**Comment by lpureenaece** [comment]
> kubectl -n <your-namespace> logs <nrf-pod-name> -c wait-mongo

![image](https://user-images.githubusercontent.com/51489848/154937473-1b77e02f-351b-4cc0-be9b-106c2647343a.png)

**Comment by lpureenaece** [comment]
I have deployed two different kubernetes cluster, one with ntw Flannel & another with Calico, Cluster with flannel ntw free5gc pods are running fine but on the cluster with Calico ntw I am getting this init issue. Have you any idea about it, Please confirm.

**Comment by ebucchianeri** [comment]
I don't think this is due to different CNI plugins. I am using Calico too, without any problems.

**Comment by raoufkh** [comment]
The idea is to try a simple application deployment on the cluster where it is malfunctioning and debug the DNS names resolution.  https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

Don't hesitate to re-open if you have more information.

Raouf
