### ISSUE TITLE
Add instrumentation for enabling Jaeger tracing

### ISSUE THREAD

**Issue by tywofxd** [Orange-OpenSource/towards5gs-helm#44]
Thank you for your great work. I have learned a lot about 5G from this project. I want to implement distributed tracing with Jaeger for researches about anomaly detection on 5G miro-service system. Could you please add instrumentation in the docker image for enabling Jaeger tracing when we deploying and testing the 5G system? I think this will help a lot for the research on 5G security. I really appreciate it if you can consider this.

**Comment by raoufkh** [comment]
Hello @tywofxd 

Instrumentation for Jaeger must be added on the NFs source code. Do you know if Free5GC team has done any updates to support that? Other alternatives consist in using a service mesh to include this functionnality (e.g. Istio). Please see [this](https://istio.io/latest/docs/tasks/observability/distributed-tracing/jaeger/) for more details.

Bests 
Raouf
