### ISSUE TITLE
Manual UE's connectivity test is Failed but helm's test result shows Succeeded

### ISSUE THREAD

**Issue by hi120ki** [Orange-OpenSource/towards5gs-helm#45]
Hi, thank you for the maintenance of this project. This project is so helpful for me.

I tried to deploy free5gc on Kubernetes with reference to [Setup free5gc on one single one and test with UERANSIM](https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/docs/demo/Setup-free5gc-and-test-with-UERANSIM.md)

> Kubernetes is single-node and single-cluster and deployed by kubedam & containerd

And I run UE's connectivity test by `helm -n free5gc test ueransim-v1` and it's result is

```
TEST SUITE:     connectivity-test-configmap
Last Started:   Fri Jul  1 07:00:37 2022
Last Completed: Fri Jul  1 07:00:37 2022
Phase:          Succeeded
TEST SUITE:     ueransim-v1-test-connection
Last Started:   Fri Jul  1 07:00:37 2022
Last Completed: Fri Jul  1 07:00:42 2022
Phase:          Succeeded
```

but I test UE's connectivity manually, a tunnel interface `uesimtun0` is created, but failed to ping check `ping -I uesimtun0 www.google.com` .

```
$ kubectl -n free5gc exec -i ueransim-v1-ue-c7c564f8c-9jlgb -- bash -c 'ping -c 10 -I uesimtun0 www.google.com'
PING www.google.com (142.250.206.228) from 10.1.0.5 uesimtun0: 56(84) bytes of data.

--- www.google.com ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9208ms

command terminated with exit code 1
```

helm's test script is defined [here](https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/charts/ueransim/templates/tests/connectivity-test.yaml#L77-L94), but it returns wrong result.

I change these script like this, and helm's test returns correct result.

```bash
    echo "Test connectivity"
    ping_output="$(kubectl -n {{ $.Release.Namespace }} exec -i ${pod_name} -- bash -c 'ping -c 10 -I uesimtun0 www.google.com')"
    echo "${ping_output}"
    echo "***********************************************************************"
    echo ""
    loss_rate="$(echo "$ping_output" | grep 'loss' | awk -F',' '{ print $3 }' | awk '{ print $1 }')"
    echo "Packet loss-rate is $loss_rate"
    if [ "$loss_rate" = "0%" ] ; then
      echo "Connection test passed - ${loss_rate}"
      exit 0
    else
      echo "Connection test failed - ${loss_rate}"
      exit 1
    fi
``` 

```
TEST SUITE:     connectivity-test-configmap
Last Started:   Fri Jul  1 07:24:14 2022
Last Completed: Fri Jul  1 07:24:14 2022
Phase:          Succeeded
TEST SUITE:     ueransim-v1-test-connection
Last Started:   Fri Jul  1 07:24:14 2022
Last Completed: Fri Jul  1 07:24:37 2022
Phase:          Failed
```

This issue is not focused on UE's connectivity, but helm's test script.

Could you give me some comments?

Thank you.

**Comment by raoufkh** [comment]
Hello 

@chabimic can you give more details on the test script please?

Bests
