### ISSUE TITLE
TUN interface created but No Connection

### ISSUE THREAD

**Issue by akram09** [Orange-OpenSource/towards5gs-helm#47]
Hello everyone, 
I wanted first to thank all the team that is maintaining such a project, it's indeed a very interesting contribution. 

I'm actually trying to deploy the free5gc on a kubernetes cluster composed of 2 worker nodes and one master, And following are the steps that I have came across in my setup: 

1. I have verified the installation of the kernel module  `gtp5g` on all the workers' nodes.
2. I currently have only one physical interface called `eth0` that I use as the master Interface for the network attachments.
3. I'm currently using kube-ovn as the CNI plugin joined with Multus.
4. In my use case I'm trying to connect a simple server with the upf :
    - The server is a simple pod that uses the same network-attachement-definition as the upf and is connected to the same network: 
  
![image](https://user-images.githubusercontent.com/31860745/178313590-4545cbf1-97b2-4506-ba6a-7452862803d2.png)

Here are the values.yml used for the deployment of free5gc charts:
```yaml
global:
  n6network:
    name: n6network
    masterIf: eth0

```
5. The ue and gnb were both deployed successfully and the interface `uesimtun0` is up and working:
![image](https://user-images.githubusercontent.com/31860745/178314250-f5fbdb4f-777c-4205-bc43-a0b7d27d39f4.png)

6. I have also activated the promicsuous mode and verified that the ipv4 forwarding is enabled on the upf pod.

## Problem 
When trying to ping from the user equipment pod to the upf everything works perfectly ( the ip address of the server is 10.100.10.10 and upf is 10.100.100.12)
![image](https://user-images.githubusercontent.com/31860745/178314484-1db92178-d9cb-4139-a7cd-9478213016c8.png)
**But ** the problem occur when trying to access the server pod from the user equipment pod:
![image](https://user-images.githubusercontent.com/31860745/178314737-24fb67ca-b290-4943-80c6-76648969742c.png)

I have checked the connection between upf and the server and it is indeed working fine: 
![image](https://user-images.githubusercontent.com/31860745/178314968-fd7f30d7-b31d-4fee-a8bb-553b223dfc3d.png)

Is there anything I'm actually missing out on in my configuration?

**Comment by raoufkh** [comment]
Hi @akram09 

Thanks first for the kind words.

Did you try to reach internet from the UE? You can try it by pinging or curling `www.google.com`

Bests
Raouf

**Comment by raoufkh** [comment]
Don't hesitate to re-open if you have extra information on networking rules
