### ISSUE TITLE
Update free5gc image

### ISSUE THREAD

**Issue by hi120ki** [Orange-OpenSource/towards5gs-helm#48]
Hi, thank you for the maintenance of this project. This project is so helpful for me.

About a month ago, free5gc released [v3.2.0](https://github.com/free5gc/free5gc/releases/tag/v3.2.0)(today's latest release is v3.2.1) that includes the migration of upf implementation from Clang to Golang.
I'd like to test how UPF that is created by Golang works in Kubernetes, but towards5gs-helm project supports v3.1.1.

Could you consider updating [free5gc images](https://hub.docker.com/u/towards5gs)?

> Would you consider publishing a Dockerfile if possible?
> I'd like to contribute to the towards5gs-helm project with image updates.
> It would be great if we could test and discuss running a new version of free5gc on kubernetes in public.

**Comment by raoufkh** [comment]
Hello @hi120ki

I updated the Free5GC container images to v3.2.0. All container images are available on our [towards5gs Dockerhub Organization](https://hub.docker.com/r/towards5gs). I've not yet created the v3.2.0 tag for our images but all latest version of Container images have been built from Free5GC v3.2.0. For example, for [UDR](https://hub.docker.com/r/towards5gs/free5gc-udr/tags), the latest version corresponds to Free5GC v3.2.0.

The next step is to update NF configurations in the Helm charts and point to the latest images (for tests) by setting the `appVersion` to latest for all Helm charts. I will do it next (I'm currently working on another topic) but if you want to contribute you're welcome I can help you. Once done, I will tag our private Github repository and workflows will tag the Docker images on DockerHub. Then, updating the project to v3.2.1 will be easier (I guess that there was no changes in configuration files).

About publishing Docker images, this is in our plans but we need to check the licenses in my company. I don't think it is feasible before September. The idea is to make all Dockerfiles in a dedicated folder within our project.

Bests
Raouf

**Comment by hi120ki** [comment]
Thank you for updating image.

I'm creating a environment for testing, and I faced a issue #49 .

Could you give me some comments? Thank you.

**Comment by hi120ki** [comment]
Hi, a PR is created.
Could you review especially about the UPF config?

Thank you.

**Comment by raoufkh** [comment]
Since the PR is already validated, I will close this issue. Many thanks for your contribution.
