### ISSUE TITLE
multiple gNB setup

### ISSUE THREAD

**Issue by pawel-gacek** [Orange-OpenSource/towards5gs-helm#53]
Hi,

Any hints for free5gc/ueransim setup/config with >1 gNB  ? to e.g. simulate handovers, cell reselection etc?

Thanks
Pawel

**Comment by raoufkh** [comment]
Hi

For a deployment with multiple gNBs, I've tested this but if you want to do it, you should instantiate the UERANSIM chart 2 times while:
- disabling the UE deployment.
- giving different IP addresses within the same network to gNB N2 interfaces
- givving differente name to gNB Kubernetes services for Radio link simulation

For the handover, I don't know if it is implemented in UERANSIM.

Raouf

**Comment by pawel-gacek** [comment]
Hi Raouf,

Ok so actually I did same way, it was working fine with 2x UERANSIM instances (taking into account changes for 2nd instance deployment).

Thanks for confirmation.
Br
Pawel
