### ISSUE TITLE
Disable NAS message encryption

### ISSUE THREAD

**Issue by ekoops** [Orange-OpenSource/towards5gs-helm#58]
Hi folks! How can I disable the NAS message encryption?

**Comment by raoufkh** [comment]
Hi

It is necessary to see the configuration of parties that send NAS messages in Free5GC and UERANSIM. I'm not sure if it's possible, but you should check.

Raouf

**Comment by ekoops** [comment]
From my understanding, the components that are involved in NAS encryption/decryption are the UE and the AMF. The AMF configuration related to the encryption is the following: https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/charts/free5gc/charts/free5gc-amf/values.yaml#L167. As we can see, the first element in the cipheringOrder list is already NEA0, so I didn't touch it (these considerations are supported by the discussion on this issue https://github.com/free5gc/free5gc/issues/47). On the UE side, the following is the configuration section that we are interested in: https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/charts/ueransim/values.yaml#L173. I set both EA1, EA2 and EA3 to false, as suggested in https://forum.free5gc.org/t/how-to-disable-a-nas-pdu-message-encryption/806 . By doing so, the UE complains about the fact that using both IA0 and EA0 is not supported if UE is not in an emergency: this is strange since I didn't set IA0 as a choice...

**Comment by raoufkh** [comment]
Thank you very much for the explanation. However, this business of using NAS without encryption is beyond me and I think it's a configuration issue. 
I'll leave the issue open if there are people interested in it.

Thanks for your understanding,
Raouf
