### ISSUE TITLE
[Question] upf container crashes using helm

### ISSUE THREAD

**Issue by Aharonez** [Orange-OpenSource/towards5gs-helm#59]
Hello,
First - thank you for this helm support.
I've been trying to set up the environment using your doc' following by:
helm -n free5gc install free5gc-v1 towards5gs/free5gc
and it seems only the upf isn't properly running:
![image](https://user-images.githubusercontent.com/32020549/197716894-75e7df61-fa99-4445-8cb3-9919e15324c5.png)

Been wondering whether it is because gtp5g dependency that must be installed on all kubernetes worker nodes? meaning needs to clone it and perform 'make' and 'make install'?
does anyone encountered this or knows how can I add gtp5g dependency on all worker nodes if that is the reason?

Thanks!

**Comment by raoufkh** [comment]
Hi

Thank you for the explanation. 

This problem seems be related to the gtp kernel module.

1) Have you installed this module on the worker node hosting the UPF?
2) Can you share UPF logs please? You can use the `kubectl logs <pod-name>` command.

Raouf

**Comment by Aharonez** [comment]
Thanks for the quick reply.
No, I haven't installed it on the worker nodes (tried to do it via ssm connection on the worker node
[upf_logs.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/9858357/upf_logs.txt)
s but couldn't even perform make install on the gtp5g package).
yes, looks like gtp5g issue; attaching log

**Comment by Aharonez** [comment]
also:
# uname -r
5.4.149-73.259.amzn2.x86_64
