### ISSUE TITLE
free5gc-nrf pod going into crash loop state

### ISSUE THREAD

**Issue by newacforwork22** [Orange-OpenSource/towards5gs-helm#63]
Hi, I'm trying to update the helm charts to pick free5gc version 3.2.1 . 

Current setup - I have free5gc NF's running successfully deployed  via towards5gs-helm charts . 

I've have pulled  free5GC v/3.2.1 source code(haven't modified any source code) and compiled the NF's to generate binaries. I'm trying to **patch the existing docker images of NFs with the new updated binaries**

For example, to update nrf binary, I took newly generated nrf binary(v/3.2.1) and built a docker image for it and updated in the existing running free5gc-nrf deployment to point to this new image and changed nrfcfg to config as new binary doesn't take nrfcfg

Below is the Dockerfile used for building nrf:0.1.1 image which is used in the free5gc-nrf deployment

FROM  towards5gs/free5gc-nrf:v3.0.6
COPY ./free5gc/bin/nrf /free5gc/nr/nrf
RUN chmod +x /free5gc/nrf/nrf

free5gc-nrf-deployment 
![image](https://user-images.githubusercontent.com/105341738/202655230-ec00b0ec-cb08-46c2-b054-42df356be150.png)
line 64 and 56

When it is updated, free5gc-nrf pod is going to crashloop state. How to resolve this?

Any help would be of great use

Attaching the logs and describe pod for reference
![image](https://user-images.githubusercontent.com/105341738/202660898-ab6726d4-cb91-4cdd-ac21-dfd84f17a3e5.png)
version is actually updated to 1.0.1, but still showing error

![image](https://user-images.githubusercontent.com/105341738/202661547-914f0047-ef12-4961-bf6e-9c12f6fa7873.png)

**Comment by raoufkh** [comment]
Hello

Free5GC Helm chart is now at v3.2.1 Free5GC's version. Thanks for the effort. I know it's not easy to update without having the Dockerfiles but I'll make the request to add them in this Git project or a separate Git project.

Bests,
Abderaouf
