### ISSUE TITLE
Add a sidecar container to NFs

### ISSUE THREAD

**Issue by hinddeep** [Orange-OpenSource/towards5gs-helm#65]
I have created a sidecar container image. I want to run this image as a sidecar container in NFs such as amf. How can I modify AMF's chart to add my sidecar container?

**Comment by raoufkh** [comment]
This is not possible by modifying only the `values.yaml` file. You have to add your containers in the `NF-deployment.yaml` file in each Helm chart.

**Comment by sanravi29** [comment]
okay, thank you for the information.

**Comment by hinddeep** [comment]
okay, thank you for the information.
