### ISSUE TITLE
UPF POD failed to create pod sandbox

### ISSUE THREAD

**Issue by ZhangZhuai** [Orange-OpenSource/towards5gs-helm#70]
I came across the problem when I deploy the free5gc project on kubernetes and I am wondering if anyone can help.
My environment is Ubuntu 20.04 and I have already install the gtp 5g module.
I follow the blog [https://prog.world/5g-core-network-deployment-with-free5gc-kubernetes-and-helm/]() and I have not change any values of the yaml.
All the other pods is runing while the upf failed.
My nic is ens33 and docker0, and I run the project on Vmware.
The detailed error information is as follows,
![WeChat Screenshot_20230226171144](https://user-images.githubusercontent.com/79315590/221401851-db1d88d0-8494-4164-bdf9-8ec6cef08be0.png)
I want to know whether the nic will affect the deployment of free5gc.And if so, how to config the network on Vmware Workstation.
Thanks!

**Comment by raoufkh** [comment]
Please refer to [Networks configuration](https://github.com/Orange-OpenSource/towards5gs-helm/tree/main/charts/free5gc#networks-configuration) while replacing `toto` by `ens33`.

**Comment by ZhangZhuai** [comment]
Sorry for having not went through the documentation carefully, and thanks a lok for you timely help.
Thanks,
Zhuai

**Comment by raoufkh** [comment]
You're welcome. I will close this issue.
