### ISSUE TITLE
Configuration in UPF and SMF in multiple cluster case

### ISSUE THREAD

**Issue by balti09** [Orange-OpenSource/towards5gs-helm#77]
Hello,
How can UPF and SMF communicate if they were deployed in different clusters ?

**Comment by raoufkh** [comment]
The current implementation relies on macvlan The underlying network is completely independent of Kubernetes. If macvlan master interfaces are within the same network then SMF and UPF will be able to cummunicate with each other. Look at this [tutorial](https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/docs/demo/Setup-free5gc-on-multiple-clusters-and-test-with-UERANSIM.md)

**Comment by balti09** [comment]
Is there any way to connect them using Kuberetes services like in the case of amf and gnb? Because I deploy the userplane in k8s cluster in azure and the  control plane in GKE. 
PS: the connection between amf and gNB has been done successfully.
