### ISSUE TITLE
Container images for NFs and UERANSIM

### ISSUE THREAD

**Issue by agr-priyanshu** [Orange-OpenSource/towards5gs-helm#8]
Hi,

The container images of NFs and UERANSIM seems to be few months old and are missing all the latest additions, bug fixes done by Free5GC and UERANSIM projects.
Is there a plan to update these images to latest builds?

Thanks
Priyanshu

**Comment by raoufkh** [comment]
Hi again @agr-priyanshu 

Free5GC v3.0.6 is now available. UERANSIM wil be updated soon!
