### ISSUE TITLE
Not able to install the free5gc on Kubernetes using helm

### ISSUE THREAD

**Issue by ashuvaid** [Orange-OpenSource/towards5gs-helm#80]
Hi 
Please can someone guide me as to how to install the free5gc on Kubernetes using helm.

I followed the procedure mentioned in the ReadMe of this project but getting below error. 

root@master:~/towards5gs-helm/charts# helm -n free5gc install 1.1.6 ./free5gc/
**Error: INSTALLATION FAILED: cannot re-use a name that is still in use**

Snapshot of my kubernetes setup is given below. I am using flannel and Multus as well

root@master:~/towards5gs-helm/charts# kubectl get pods -A
NAMESPACE      NAME                             READY   STATUS    RESTARTS      AGE
kube-flannel   kube-flannel-ds-vjlgs            1/1     Running   0             26m
kube-flannel   kube-flannel-ds-xrzn9            1/1     Running   0             26m
kube-system    coredns-565d847f94-6796r         1/1     Running   0             63m
kube-system    coredns-565d847f94-prnw8         1/1     Running   0             63m
kube-system    etcd-master                      1/1     Running   0             63m
kube-system    kube-apiserver-master            1/1     Running   0             63m
kube-system    kube-controller-manager-master   1/1     Running   0             63m
kube-system    kube-multus-ds-kbp5c             1/1     Running   3 (28m ago)   35m
kube-system    kube-multus-ds-n2jzj             1/1     Running   3 (27m ago)   35m
kube-system    kube-proxy-7lclr                 1/1     Running   0             63m
kube-system    kube-proxy-n6hvv                 1/1     Running   0             61m
kube-system    kube-scheduler-master            1/1     Running   0             63m
root@master:~/towards5gs-helm/charts# kubectl get nodes
NAME     STATUS   ROLES           AGE   VERSION
master   Ready    control-plane   63m   v1.25.6
worker   Ready    <none>          61m   v1.25.6
root@master:~/towards5gs-helm/charts#

Also please guide me as to how I can change the physical interface name to eth0 and eth1.

**Comment by TJKkking** [comment]
Maybe you can refer to [`here`](https://github.com/helm/helm/issues/3134#issuecomment-344094420)
`helm upgrade --install`

**Comment by ashuvaid** [comment]
On another VM I have set up flannel as CNI along with MULTUS to meet the multiple ethernet (eth) interfaces requirement. On that setup as well following PODS fail to reach RUNNING state. Logs of each are given below. Let me know what needs to be addressed to resolve these errors

root@master:~# kubectl get pods -n free5gc | grep -iv running
NAME                                                    READY   STATUS              RESTARTS        AGE
free5gc-v1-free5gc-amf-amf-88784d6d4-qmwlw              0/1     Init:0/1            0               18m
free5gc-v1-free5gc-ausf-ausf-cf974b9cc-5j6rm            0/1     CrashLoopBackOff    7 (4m19s ago)   18m
free5gc-v1-free5gc-pcf-pcf-7f968d556c-9669f             0/1     CrashLoopBackOff    7 (4m27s ago)   18m
free5gc-v1-free5gc-smf-smf-57bbfd4cdd-6p8cc             0/1     Init:0/1            0               18m
free5gc-v1-free5gc-udm-udm-54c7857d7b-ghzbt             0/1     CrashLoopBackOff    7 (4m17s ago)   18m
free5gc-v1-free5gc-upf-upf-57c6c59d8b-58sd5             0/1     ContainerCreating   0               18m




root@master:~# kubectl logs free5gc-v1-free5gc-pcf-pcf-7f968d556c-9669f -c pcf -n free5gc
PCF Run Error: Failed to initialize !!
2023-03-20T14:00:24Z [INFO][PCF][CFG] config version [1.0.1]
2023-03-20T14:00:24Z [ERRO][PCF][CFG] Invalid RegisterIPv4: non zero value required
2023-03-20T14:00:24Z [ERRO][PCF][CFG] [-- PLEASE REFER TO SAMPLE CONFIG FILE COMMENTS --]

root@master:~# kubectl logs free5gc-v1-free5gc-amf-amf-88784d6d4-qmwlw -c amf -n free5gc
Error from server (BadRequest): container "amf" in pod "free5gc-v1-free5gc-amf-amf-88784d6d4-qmwlw" is waiting to start: PodInitializing

root@master:~# kubectl logs free5gc-v1-free5gc-smf-smf-57bbfd4cdd-6p8cc -c smf -n free5gc
Error from server (BadRequest): container "smf" in pod "free5gc-v1-free5gc-smf-smf-57bbfd4cdd-6p8cc" is waiting to start: PodInitializing


root@master:~# kubectl logs free5gc-v1-free5gc-ausf-ausf-cf974b9cc-5j6rm -c ausf -n free5gc
2023-03-20T14:00:18Z [INFO][AUSF][CFG] config version [1.0.2]
2023-03-20T14:00:18Z [ERRO][AUSF][CFG] Invalid RegisterIPv4: non zero value required
2023-03-20T14:00:18Z [ERRO][AUSF][CFG] [-- PLEASE REFER TO SAMPLE CONFIG FILE COMMENTS --]
2023-03-20T14:00:18Z [ERRO][AUSF][App] AUSF Run error: Failed to initialize !!


root@master:~# kubectl logs free5gc-v1-free5gc-udm-udm-54c7857d7b-ghzbt  -c udm -n free5gc
2023-03-20T14:05:41Z [INFO][UDM][CFG] config version [1.0.2]
2023-03-20T14:05:41Z [ERRO][UDM][CFG] RegisterIPv4: non zero value required
2023-03-20T14:05:41Z [ERRO][UDM][CFG] [-- PLEASE REFER TO SAMPLE CONFIG FILE COMMENTS --]
UDM Run error: Failed to initialize !!


root@master:~# kubectl logs free5gc-v1-free5gc-upf-upf-57c6c59d8b-58sd5  -c upf -n free5gc
Error from server (BadRequest): container "upf" in pod "free5gc-v1-free5gc-upf-upf-57c6c59d8b-58sd5" is waiting to start: ContainerCreating
