### ISSUE TITLE
AMF and SMF pods started container wait-nrf

### ISSUE THREAD

**Issue by sergirem** [Orange-OpenSource/towards5gs-helm#85]
Hello! 

I want to deploy pods on the Kubernetes cluster, and AMF and SMF functions are stuck on Init:0/1. I tried to describe the cluster, but the reason these pods don't initiate is because is waiting for somer reason the NRF function. 

I tried to delete AMF, SMF and NRF functions to try initialise them again but I didn't get any result. 

Can someone help with te reason and how I can fix it?

Thank you beforehand!

**Comment by sergirem** [comment]
<img width="549" alt="Screenshot 2023-05-30 at 16 21 48" src="https://github.com/Orange-OpenSource/towards5gs-helm/assets/123004147/5e2c626f-fc39-4061-a9f6-94a6bdb7291a">

**Comment by hackeryounow** [comment]
The same problems have occurred in my cluster, but only  in smf.
Kubernetes Version: 1.23.0

**Comment by hackeryounow** [comment]
Standalone kubernetes cluster

**Comment by hackeryounow** [comment]
I have solved it.

https://github.com/Orange-OpenSource/towards5gs-helm/issues/74

**Comment by raoufkh** [comment]
Thanks! I will close the issue!
