### ISSUE TITLE
Unable to deploy free5gc with helm

### ISSUE THREAD

**Issue by lzyxx77** [Orange-OpenSource/towards5gs-helm#88]
After using helm to deploy free5gc, the pod has been unable to run. When describing the pod, I found that it failed to pull image "towards5gs/initURL: 1.0.0"

**Comment by twotigeres** [comment]
NAMESPACE      NAME                                           READY   STATUS                  RESTARTS         AGE
free5gc        free5gc-free5gc-amf-amf-6c78646c5f-mtfxn       0/1     Init:0/1                0                13m
free5gc        free5gc-free5gc-ausf-ausf-78fb9bfdb9-jlhw2     0/1     Init:ImagePullBackOff   0                13m
free5gc        free5gc-free5gc-nrf-nrf-65fd5ddd8d-xddb8       0/1     Init:0/1                0                13m
free5gc        free5gc-free5gc-nssf-nssf-5f79c79dbb-ddzmp     0/1     Init:ImagePullBackOff   0                13m
free5gc        free5gc-free5gc-pcf-pcf-859df96b99-4zdlp       0/1     Init:ImagePullBackOff   0                13m
free5gc        free5gc-free5gc-smf-smf-78cc9db667-mbktx       0/1     Init:ImagePullBackOff   0                13m
free5gc        free5gc-free5gc-udm-udm-9d98f7587-srdq5        0/1     Init:ImagePullBackOff   0                13m
free5gc        free5gc-free5gc-udr-udr-57c899d979-hgc4p       0/1     Init:ImagePullBackOff   0                13m
free5gc        free5gc-free5gc-upf-upf-575fc989df-plsf8       0/1     ImagePullBackOff        0                13m
free5gc        free5gc-free5gc-webui-webui-7454f58766-kb554   0/1     Init:0/1                0                13m


Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       14m                    default-scheduler  Successfully assigned free5gc/free5gc-free5gc-nssf-nssf-5f79c79dbb-ddzmp to k8s-slave
  Normal   AddedInterface  14m                    multus             Add eth0 [10.244.1.228/24] from cbr0
  Warning  Failed          9m58s                  kubelet            Failed to pull image "towards5gs/initcurl:1.0.0": rpc error: code = Unknown desc = context canceled
  Warning  Failed          9m58s                  kubelet            Error: ErrImagePull
  Normal   SandboxChanged  9m57s                  kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   AddedInterface  9m56s                  multus             Add eth0 [10.244.1.236/24] from cbr0
  Warning  Failed          9m55s (x3 over 9m56s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff         9m55s (x3 over 9m56s)  kubelet            Back-off pulling image "towards5gs/initcurl:1.0.0"
  Normal   Pulling         9m44s (x2 over 14m)    kubelet            Pulling image "towards5gs/initcurl:1.0.0"

**Comment by raoufkh** [comment]
The image is present [here](https://hub.docker.com/r/towards5gs/initcurl/tags). Can you check the internet connection in your cluster?
