### ISSUE TITLE
n6 connecticity when nagp is NodePort 

### ISSUE THREAD

**Issue by hackeryounow** [Orange-OpenSource/towards5gs-helm#94]
`nr-ue` and `nr-gnb` are not run in pod, and then `ping -I uesimtun0 google.com` failed.

I wonder know whether this could be solved by changing the helm charts files.

**Comment by raoufkh** [comment]
Hello @hackeryounow! If you deploy gNB outside the cluster, you can use an N3 interface that in the same network as UPF N3 interface. If you don't have one, you can create an ipvlan or macvlan interface and use it.

For example:
```bash
sudo ip link add link eth0 name n3 type ipvlan mode l2 && \
    sudo ip addr add 10.100.50.236/29 dev n3 && \
    sudo ip link set n3 up
```
Knowing that eth0 is within the same network as the master interface of UPF N3 interface.

Additional N3 interface is attached using Multus for network isolation and providing the possibility for network accelaration (later, we could add the possibility of using SRIOV).
