### ISSUE TITLE
Failure to Create UPF Container

### ISSUE THREAD

**Issue by ChoB100** [Orange-OpenSource/towards5gs-helm#97]
I cannot create a UPF container using `kubectl`.

![image](https://github.com/Orange-OpenSource/towards5gs-helm/assets/32658458/04d8e68c-c134-4e64-8eb0-8c4ab83e2ace)

I followed the free5gc official tutorial below.
- Link: [https://free5gc.org/blog/IntroduceKubernetesAndDeploymentfree5GConKubernetesWithHelm/main/#install-free5gc-and-ueransim](url)

This is my 5th try, but it's not working, what can I do to fix this?

**Comment by s111753164** [comment]
I also encountered the same problem...

**Comment by Kushan-Nilanga** [comment]
I am also encountering the same issue.

**Comment by mickwubs97** [comment]
I have the same problem. I tried "kubectl describe --namespace free5gc pod [pod name] and got:

 Normal   AddedInterface          1s                      multus             Add eth0 [10.244.0.169/24] from cbr0
  Normal   AddedInterface          1s                      multus             Add n3 [10.100.50.233/29] from free5gc/n3network-free5gc-v1-free5gc-upf

seems that I am having problems adding n3 and eht0 (perhaps n6) interfaces.

Any suggestions? 

Thanks.

**Comment by devopsjourney23** [comment]
I've created Complete Installation of this 5GC from scratch. You may look into this video.

https://www.youtube.com/watch?v=ZMGsWStz090&t=853s

**Comment by krupalb** [comment]
@devopsjourney23 what is your host machine based on and what hyperv are you using?

**Comment by devopsjourney23** [comment]
@krupalb , I've tried Host Machine as both Windows and Ubuntu. Also Oracle VirtualBox/VMware works fine. If you still have any issues, ping me, will try to look into this together.

**Comment by mickwubs97** [comment]
I think this maybe have something to do with the minikube. I tried with [microK8s](https://microk8s.io/docs/getting-started) instead of minikube and now the UPF is working. It seems to me that upf cannot find node interface inside the minikube. I am using ubuntu20.04 server.

**Comment by mickwubs97** [comment]
I solved this issue by using microk8s and setting the gateway IP of n6 network to the IP of the gateway of the host interface(not the IP of the actual interface). I tried a microk8s deployment on Ubuntu20.04 VM running on VirtualBox7.0 with a second interface on K8s node, the process is documented [here](https://github.com/mickwubs97/free5gcdeploy).

**Comment by hasanyeganeh** [comment]
Also you may use different VM for UPF, in my case i wanted to use it for commercial test and i created different VM for UPF and deployed all CP function on kubernetees
