### ISSUE TITLE
UPF and SMF Pods are in crashloopbackoff state and fail to start.

### ISSUE THREAD

**Issue by devopsjourney23** [Orange-OpenSource/towards5gs-helm#98]
Hi,

I'm trying to install 5gs on k8s cluster which is on ubuntu 20.04. building gtp5g was successful with kernal "5.4.0-159-generic"

In values.yaml, I've modified eth0/eth1 with ens33/ens34 interface name. Attaching, ip-info, upf-logs, smf-logs, all k8s pod in all namespaces. Appreciate if someone can point me in right direction and help sort this out.

[upf-logs.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/12491763/upf-logs.txt)
[ip-info.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/12491764/ip-info.txt)
[k8s-pod-details.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/12491765/k8s-pod-details.txt)
[smf-logs.txt](https://github.com/Orange-OpenSource/towards5gs-helm/files/12491766/smf-logs.txt)

**Comment by devopsjourney23** [comment]
After couple of tries of install helm chats, primarily issue is with UPF. Seeing below error.
`2023-09-01T07:27:12.748483949Z [INFO][UPF][CFG] ==================================================
2023-09-01T07:27:12.748493158Z [INFO][UPF][Main] Log level is set to [info]
2023-09-01T07:27:12.748501178Z [INFO][UPF][Main] Report Caller is set to [false]
2023-09-01T07:27:12.748580507Z [INFO][UPF][Main] starting Gtpu Forwarder [gtp5g]
2023-09-01T07:27:12.748596109Z [INFO][UPF][Main] GTP Address: "172.17.192.233:2152"
2023-09-01T07:27:12.819948480Z [ERRO][UPF][Main] UPF Cli Run Error: open Gtp5g: version mismatch: operation not supported`

**Comment by devopsjourney23** [comment]
It was related to some k8s networking issue coupled with cni plugins. It's all sorted and able to install successfully.

**Comment by devopsjourney23** [comment]
It was related to some k8s networking issue coupled with cni plugins. It's all sorted and able to install successfully.

**Comment by pragyasharmaa** [comment]
Could you tell how you solved this issue? I too am getting this error.
`2024-02-22T15:36:38.311798524Z [INFO][UPF][Main] GTP Address: "10.100.50.233:2152"
 2024-02-22T15:36:38.346010774Z [ERRO][UPF][Main] UPF Cli Run Error: open Gtp5g: version mismatch: operation not supported`

**Comment by devopsjourney23** [comment]
You can refer to my demo on youtube.
https://www.youtube.com/watch?v=ZMGsWStz090&t=2576s
